version: '3.8'

services:
  postgres:
    image: postgres
    container_name: orientamais-postgres
    restart: always
    environment:
      POSTGRES_USER: orientamais
      POSTGRES_PASSWORD: orientamais
      POSTGRES_DB: orientamais
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
