# Application
spring.application.name=orientamais
spring.profiles.active=dev

# JPA / Hibernate (comum)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.umc.pfc.orientamais=DEBUG
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO

# Cors
origins.webapp=http://localhost:4200

# Application-specific
app.registration.url=http://localhost:4200/register/
app.reset-password.url=http://localhost:4200/reset-password
app.reset-password.ttl-seconds=86400
