ALTER TABLE class
    ADD COLUMN IF NOT EXISTS external_event_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE class
    ALTER COLUMN end_time SET NOT NULL;